---
abstract: 'L<ElasticSearch> based session engine for Dancer'
author:
  - 'Big Angry Blue Fish <babf@cpan.org>'
build_requires:
  ElasticSearch::TestServer: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Session-ElasticSearch
requires:
  Dancer: 0
  Dancer::Session::Abstract: 0
  Digest::HMAC_SHA1: 0
  ElasticSearch: 0
  Try::Tiny: 0
  base: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
version: 1.007
